from .error_handling import SimulationError
from .Graph import Graph, Zone, Drone, Connection
from collections import deque
import heapq
from collections import defaultdict

class Simulation:
    def __init__(self, graph: Graph):
        self.graph = graph
        self.path = []

    def run(self):
        """
            Simulate the Drones movments in one path :) .
        """
        path = self.djikstra(self.graph.start, self.graph.end)
        for drone in self.graph.drones:
            drone.path = path
        """To print the path that generated by djikstra :) ."""
        # for zone in path[0:-2]:
        #     print(zone.name, " ===> ", end="")
        # print(path[-1].name)
        turns = 1
        while not self.graph.is_over():
            moves = []
            print(f"\nTurn {turns}")
            for drone in self.graph.drones:
                if drone.finish:
                    continue
                
                index = drone.index
                next_zone = drone.get_next_zone()
                Con = drone.path[index].connections.get(next_zone.name)
                
                if self.can_move(next_zone, Con):
                    moves.append((drone, next_zone, Con))
                    next_zone.in_coming += 1
                    Con.to_delever += 1
                    # print(next_zone.in_coming, Con.to_delever)
            
            for drone, next_zone, Con in moves:
                drone.move_drone()
                next_zone.in_coming -= 1
                Con.to_delever -= 1
                print("#",drone, "To", next_zone.name,f"Zone capacity: {next_zone.max_drones}", f"connection capacity: {Con.capacity}", next_zone.drones)
            
            turns += 1


    
    def can_move(self, destination: Zone,
                 connection: Connection)-> bool:
        if connection.can_delever() and destination.kayn_tisa3():
                # print(destination.in_coming, connection.to_delever)
                return True
        return False






    def graph_validate(self) -> list[Zone] | None:
        path = self.bfs_search(self.graph.start, self.graph.end)
        if not path:
            raise SimulationError(
                "There is no path between start and end point .")
        print(path)

    def bfs_search(self, start: Zone, target: Zone):
        queue = deque([start])
        visited = {start}
        parent = {start: None}

        while queue:
            zone = queue.popleft()

            if zone == target:
                path = []
                total = 0
                while zone is not None:
                    total += zone.get_cost()
                    path.append((zone.name, zone.get_cost()))
                    zone = parent[zone]
                return path[::-1], f"Total is {total - 1}"

            for connection in zone.connections.values():
                n = connection.first if connection.first != zone\
                    else connection.second
                if n not in visited or n.zone_type == "blocked":
                    visited.add(n)
                    parent[n] = zone
                    queue.append(n)
        return "Not Foud"

    def djikstra(self, start: Zone, target: Zone) -> list[Zone] | None:
        """
            Find The most cheapest Path from stariting slected Zone to a target Zone :)
        """
        visited = set()
        parent = {start: None}
        distance = defaultdict(lambda: float("inf"))
        distance[start] = 0
        queue = []
        path = []

        heapq.heappush(queue, (0, start.name))

        while queue:
            cost, zone = heapq.heappop(queue)

            zone = self.graph.zones[zone]
            if zone in visited:
                continue
            visited.add(zone)


            if zone == target:
                total = 0
                while zone:
                    # total += zone.get_cost()
                    path.append(zone)
                    zone = parent[zone]
                return path[::-1]

            for neighbor in zone.connections.values():
                neighbor = neighbor.first if neighbor.first != zone else neighbor.second
                
                if neighbor.zone_type == "blocked":
                    continue
                
                if neighbor.zone_type == "priority":
                    cost = 0.9
                else:
                    cost = neighbor.get_cost()
                new_dis = distance[zone] + cost

                if distance[neighbor] > new_dis:
                    distance[neighbor] = new_dis
                    parent[neighbor] = zone
                    heapq.heappush(queue, (new_dis, neighbor.name))
        
        
        return "Not Founnnd"